Repository codestates-seb/seb42_main_002, pull requests merged in 2023-03, with the labels that each got.

#6 Be feat/entity mapping ming
  back/src/main/java/com/mainproject/back/BackApplication.java
  back/src/main/java/com/mainproject/back/ban/entity/Ban.java
  back/src/main/java/com/mainproject/back/follow/entity/Follow.java
  back/src/main/java/com/mainproject/back/language/entity/Language.java
  back/src/main/java/com/mainproject/back/letter/entity/Letter.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/language/MemberLanguage.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/tag/MemberTag.java
  back/src/main/java/com/mainproject/back/tag/entity/Tag.java
  back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
  back/src/main/resources/application.yml
Labels: enhancement, BE

#19 feat: 레이아웃 기초 틀 작업
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/assets/base_texture.svg
  front/src/assets/envelope_line.svg
  front/src/components/Intro/Intro.tsx
  front/src/components/Layouts/BaseLayout.module.scss
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Layouts/Nav/BottomNavBar.module.scss
  front/src/components/Layouts/Nav/BottomNavBar.tsx
  front/src/components/Layouts/NoneLayout.tsx
  front/src/components/Main/Main.module.css
  front/src/components/Main/Main.module.scss
  front/src/components/Main/Main.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/context/auth-context.tsx
  front/src/dummy/users.ts
  front/src/global.d.ts
  front/src/hooks/useLocalStorage.ts
  front/src/index.css
  front/src/utils/enums/index.ts
  front/src/utils/enums/test.enum.ts
  front/src/utils/index.ts
  front/src/utils/types/auth/index.ts
  front/src/utils/types/auth/sign-in.type.ts
  front/src/utils/types/index.ts
  front/src/utils/types/users/index.ts
  front/src/utils/types/users/user.type.ts
Labels: FE

#22 feat : member Crud_gri
  back/build.gradle
  back/src/main/java/com/mainproject/back/helper/UriCreator.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/resources/application.yml
Labels: enhancement, BE

#24 Be feat/vocabulary jin
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
  back/src/main/java/com/mainproject/back/vocabulary/exception/VocabExceptionCode.java
  back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
  back/src/main/java/com/mainproject/back/vocabulary/repository/VocabRepository.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
Labels: BE

#27 chore: axios, swiper 패키지 추가
  front/package-lock.json
  front/package.json
Labels: FE

#25 feat : Member_Post_회원가입시_멤버상태_변경로직_구현_gri
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
Labels: BE

#39 feat:tag기능 추가
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
  back/src/main/java/com/mainproject/back/member/dto/MemberTagDto.java
  back/src/main/java/com/mainproject/back/member/dto/MemberTagPatchDto.java
  back/src/main/java/com/mainproject/back/member/dto/MemberTagResponseDto.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/repository/MemberTagRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/member/tag/MemberTag.java
  back/src/main/java/com/mainproject/back/tag/repository/TagRepository.java
Labels: BE

#35 [FE] 버튼 및 라벨 및 모달 공통 컴포넌트 작업
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/Common/Button/Button.module.scss
  front/src/components/Common/Button/Button.tsx
  front/src/components/Common/Button/ButtonGroup.module.scss
  front/src/components/Common/Button/ButtonGroup.tsx
  front/src/components/Common/Label/Label.module.scss
  front/src/components/Common/Label/Label.tsx
  front/src/components/Common/Modal/AlertModal.module.scss
  front/src/components/Common/Modal/AlertModal.tsx
  front/src/components/Common/Modal/FullPageModal.module.scss
  front/src/components/Common/Modal/FullPageModal.tsx
  front/src/components/Common/Modal/Modal.tsx
  front/src/components/Common/RoundProfile/RoundProfile.module.scss
  front/src/components/Guide/Guide.module.scss
  front/src/components/Guide/GuideBox.tsx
  front/src/components/Guide/GuideSection.tsx
  front/src/components/Intro/Intro.tsx
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Layouts/NoneLayout.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/context/AuthContext.tsx
  front/src/context/ModalContext.tsx
  front/src/hooks/useLocalStorage.ts
  front/src/hooks/useModals.ts
  front/src/index.css
  front/src/pages/GuidePage.tsx
  front/src/pages/MainPage.tsx
Labels: FE

#41 feat: 회원 정보 수정
  back/src/main/java/com/mainproject/back/language/dto/MemberLanguageDto.java
  back/src/main/java/com/mainproject/back/language/entity/Language.java
  back/src/main/java/com/mainproject/back/language/entity/MemberLanguage.java
  back/src/main/java/com/mainproject/back/language/exception/LanguageExceptionCode.java
  back/src/main/java/com/mainproject/back/language/service/LanguageService.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/exception/MemberExceptionCode.java
  back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
  back/src/main/java/com/mainproject/back/member/repository/MemberTagRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/tag/entity/MemberTag.java
  back/src/main/java/com/mainproject/back/tag/entity/Tag.java
  back/src/main/java/com/mainproject/back/tag/exception/TagExceptionCode.java
  back/src/main/java/com/mainproject/back/tag/service/TagService.java
Labels: BE

#46 Be feat/spring security+jwt jin
  back/build.gradle
  back/src/main/java/com/mainproject/back/block/controller/BlockController.java
  back/src/main/java/com/mainproject/back/block/dto/BlockDto.java
  back/src/main/java/com/mainproject/back/block/entity/Block.java
  back/src/main/java/com/mainproject/back/block/entity/BlockMapper.java
  back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
  back/src/main/java/com/mainproject/back/block/service/BlockService.java
  back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/exception/MemberExceptionCode.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/security/config/SecurityConfiguration.java
  back/src/main/java/com/mainproject/back/security/dto/LoginDto.java
  back/src/main/java/com/mainproject/back/security/filter/JwtAuthenticationFilter.java
  back/src/main/java/com/mainproject/back/security/filter/JwtVerificationFilter.java
  back/src/main/java/com/mainproject/back/security/handler/MemberAccessDeniedHandler.java
  back/src/main/java/com/mainproject/back/security/handler/MemberAuthenticationEntryPoint.java
  back/src/main/java/com/mainproject/back/security/handler/MemberAuthenticationFailureHandler.java
  back/src/main/java/com/mainproject/back/security/handler/MemberAuthenticationSuccessHandler.java
  back/src/main/java/com/mainproject/back/security/jwt/JwtTokenizer.java
  back/src/main/java/com/mainproject/back/security/userdetails/MemberDetailsService.java
  back/src/main/java/com/mainproject/back/security/utils/AuthorityUtils.java
  back/src/main/java/com/mainproject/back/security/utils/ErrorResponder.java
  back/src/main/resources/application.yml
Labels: BE

#47 feat : vocabulary에 principal 추가
  back/src/main/java/com/mainproject/back/member/exception/MemberExceptionCode.java
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
Labels: BE

#60 Be fix/get vocab blcok list fix jin
  back/src/main/java/com/mainproject/back/block/controller/BlockController.java
  back/src/main/java/com/mainproject/back/block/dto/BlockDto.java
  back/src/main/java/com/mainproject/back/block/mapper/BlockMapper.java
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
Labels: BE

#64 feat : 추천 친구 조회 기능
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberRecommendDto.java
  back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
Labels: BE

#61 Fe feat/black list ayo #58
  front/src/App.tsx
  front/src/components/BlackList/BlackList.module.scss
  front/src/components/BlackList/BlackList.tsx
  front/src/components/Common/UserCard/UserCard.tsx
  front/src/components/Following/Following.tsx
  front/src/dummy/userList.ts
  front/src/pages/BlackListPage.tsx
  front/src/utils/types/users/user.type.ts
Labels: FE

#65 feat : limit 추가
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
Labels: BE

#66 Fe feat/voca ayo 단어장 모달 & 단어장 리스트 페이지 #62
  front/src/App.tsx
  front/src/components/Voca/Voca.module.scss
  front/src/components/Voca/Voca.tsx
  front/src/components/Voca/VocaCard/VocaCard.module.scss
  front/src/components/Voca/VocaCard/VocaCard.tsx
  front/src/components/Voca/VocaModal/VocaModal.module.scss
  front/src/components/Voca/VocaModal/VocaModal.tsx
  front/src/dummy/voca.ts
  front/src/index.css
  front/src/pages/VocaPage.tsx
  front/src/utils/types/voca/index.ts
  front/src/utils/types/voca/voca.type.ts
Labels: FE

#69 Fe feat/component ria
  front/package-lock.json
  front/package.json
  front/src/assets/img/flags/flag_cn.svg
  front/src/assets/img/flags/flag_es.svg
  front/src/assets/img/flags/flag_jp.svg
  front/src/assets/img/flags/flag_kr.svg
  front/src/assets/img/flags/flag_us.svg
Labels: FE

#73 feat: common type export 파일 추가 & profile 상세 페이지 라우터 및 컴포넌트 생성성
  front/src/App.tsx
  front/src/components/Profile/ProfilePage.tsx
  front/src/utils/types/common/index.ts
  front/src/utils/types/index.ts
Labels: FE

#75 [FE] feat: 프로필 상세페이지 추가
  front/src/App.tsx
  front/src/components/Common/Button/Button.module.scss
  front/src/components/Common/Button/Button.tsx
  front/src/components/Common/Flex/Flex.module.scss
  front/src/components/Common/Flex/Flex.tsx
  front/src/components/Common/InfoGroup/InfoGroup.module.scss
  front/src/components/Common/InfoGroup/InfoGroup.tsx
  front/src/components/Common/InputFeild/InputFeild.module.scss
  front/src/components/Common/InputFeild/InputFeild.tsx
  front/src/components/Common/Label/Label.module.scss
  front/src/components/Common/Label/Label.tsx
  front/src/components/Common/ProfileBaseInfo/ProfileBaseInfo.module.scss
  front/src/components/Common/ProfileBaseInfo/ProfileBaseInfo.tsx
  front/src/components/Common/ProfileCard/ProfileCard.module.scss
  front/src/components/Common/ProfileCard/ProfileCard.module.tsx
  front/src/components/Common/ProfileExtraInfo/ProfileExtraInfo.module.scss
  front/src/components/Common/ProfileExtraInfo/ProfileExtraInfo.tsx
  front/src/components/Common/ProfileImage/ProfileImage.module.scss
  front/src/components/Common/ProfileImage/ProfileImage.tsx
  front/src/components/Common/RadioButton/RadioButtonGroup.tsx
  front/src/components/Common/RadioButton/RadioGroup.module.scss
  front/src/components/Common/Row/Row.tsx
  front/src/components/Common/TextAreaFeild/TextAreaFeild.module.scss
  front/src/components/Common/TextAreaFeild/TextAreaFeild.tsx
  front/src/components/Layouts/BaseLayout.module.scss
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Layouts/Nav/BottomNavBar.module.scss
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LanguageSearchModal/LanguageSearchList.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.module.scss
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Profile/Profile.module.scss
  front/src/components/Profile/Profile.tsx
  front/src/components/Profile/ProfilePage.tsx
  front/src/index.css
  front/src/pages/MyProfilePage.tsx
  front/src/pages/ProfilePage.tsx
  front/src/recoil/atoms/user/user.ts
  front/src/recoil/atoms/user/userLanguage.ts
  front/src/recoil/atoms/user/userLocation.ts
  front/src/recoil/atoms/user/userTag.ts
  front/src/utils/common/index.ts
  front/src/utils/enums/common/common.enum.ts
  front/src/utils/types/common/common.type.ts
Labels: FE

#80 feat: 편지 목록에서 편지 클릭 로직에 리코일 추가
  front/src/components/Common/UserCard/UserCard.tsx
  front/src/components/Letter/LetterList.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/Letter/LetterWrapper/LetterWrapper.tsx
  front/src/recoil/atoms/index.ts
  front/src/recoil/atoms/letter/index.ts
  front/src/recoil/atoms/letter/letter.ts
Labels: FE

#94 feat: cors 설정 추가
  back/src/main/java/com/mainproject/back/security/config/SecurityConfiguration.java
Labels: BE

#86 feat: 마이프로필 recoil 적용 (언어 제외)
  front/src/components/Common/LabelButton/LabelButton.module.scss
  front/src/components/Common/LabelButton/LabelButton.tsx
  front/src/components/Common/Modal/FullPageModal.tsx
  front/src/components/Common/ProfileImage/ProfileImage.module.scss
  front/src/components/Common/SearchInput/SearchInput.module.scss
  front/src/components/Common/SearchInput/SearchInput.tsx
  front/src/components/Common/Tags/TagsModal.tsx
  front/src/components/Common/TextAreaFeild/TextAreaFeild.module.scss
  front/src/components/Layouts/BaseLayout.module.scss
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LanguageSearchModal/LanguageSearchList.tsx
  front/src/components/MyProfile/LanguageSearchModal/LanguageSearchModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.module.scss
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Profile/Profile.tsx
  front/src/dummy/Tags.tsx
  front/src/dummy/users.ts
  front/src/hooks/useModals.ts
  front/src/recoil/atoms/index.ts
  front/src/recoil/atoms/user/index.ts
  front/src/recoil/atoms/user/userLanguage.ts
  front/src/recoil/atoms/user/userLocation.ts
  front/src/recoil/selectors/user/user.ts
  front/src/reducers/userReducer/index.ts
  front/src/utils/common/index.ts
  front/src/utils/enums/common/common.enum.ts
  front/src/utils/enums/common/index.ts
  front/src/utils/enums/index.ts
  front/src/utils/enums/user/index.ts
  front/src/utils/enums/user/user.enum.ts
  front/src/utils/types/common/common.type.ts
  front/src/utils/types/tags/tags.ts
  front/src/utils/types/users/user.type.ts
Labels: FE

#98 feat: 폰트 적용
  front/src/assets/fonts/CookieRun-Regular.woff2
  front/src/assets/fonts/MV-Boil.woff2
  front/src/components/Common/Button/Button.module.scss
  front/src/components/Common/InfoGroup/InfoGroup.module.scss
  front/src/components/Common/PageTitle/PageTitle.module.scss
  front/src/components/Main/LifeQuotes/LifeQuotes.module.scss
  front/src/components/Main/MainTitle.module.scss
  front/src/components/Main/RecomandUser/RecomandUser.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/index.css
Labels: FE

#100 feat : Member/Letter/Vocabulary 테스트 코드 추가 + test/applicaton.yml 추가
  back/build.gradle
  back/src/main/java/com/mainproject/back/letter/dto/LetterCountDto.java
  back/src/main/java/com/mainproject/back/letter/dto/LetterPostDto.java
  back/src/main/java/com/mainproject/back/letter/service/LetterService.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
  back/src/test/java/com/mainproject/back/letter/LetterControllerTest.java
  back/src/test/java/com/mainproject/back/letter/repository/LetterRepositoryTest.java
  back/src/test/java/com/mainproject/back/member/MemberControllerTest.java
  back/src/test/java/com/mainproject/back/vocabulary/VocabularyControllerTest.java
  back/src/test/resources/application.yml
Labels: BE

#101 fix: 인트로 페이지 및 기타 css 수정
  front/src/assets/img/common/btn_primary.svg
  front/src/assets/img/common/btn_secondary.svg
  front/src/assets/img/intro/mailIcon.svg
  front/src/assets/img/intro/owlIcon.svg
  front/src/assets/img/intro/owls_body.svg
  front/src/assets/img/intro/owls_head.svg
  front/src/assets/img/intro/owls_wing_left.svg
  front/src/assets/img/intro/owls_wing_right.svg
  front/src/assets/img/intro/speech_bubble.svg
  front/src/components/Common/Button/Button.module.scss
  front/src/components/Common/Modal/AlertModal.module.scss
  front/src/components/Guide/Guide.module.scss
  front/src/components/Intro/Intro.module.scss
  front/src/components/Intro/Intro.tsx
  front/src/components/Login/LoginMain.module.scss
  front/src/components/SignUp/SignUp.module.scss
  front/src/pages/GuidePage.tsx
Labels: FE

#105 feat: 첫 로그인 후 프로필 설정 모달 리코일 작업
  front/src/App.tsx
  front/src/components/Common/SummaryTitle/SummaryTitle.module.scss
  front/src/components/Common/SummaryTitle/SummaryTitle.tsx
  front/src/components/Intro/Intro.module.scss
  front/src/components/Login/LoginMain.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LanguageSearchModal/LanguageSearchModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/ProfileCompleted/Welcom.tsx
  front/src/components/Start/Start.module.scss
  front/src/components/Start/Start.tsx
  front/src/components/Welcome/Welcome.module.scss
  front/src/components/Welcome/Welcome.tsx
  front/src/dummy/Tags.tsx
  front/src/dummy/users.ts
  front/src/pages/StartPage.tsx
  front/src/pages/WelcomPage.tsx
  front/src/recoil/atoms/user/user.ts
  front/src/recoil/atoms/user/userLocation.ts
  front/src/utils/types/common/common.type.ts
  front/src/utils/types/users/user.type.ts
Labels: FE

#107 [FE] 검색 페이지 마크업 & 리코일 작업
  front/src/App.tsx
  front/src/components/Common/LetterStatusIcon/LetterStatusIcon.module.scss
  front/src/components/Common/PageTitle/PageTitle.module.scss
  front/src/components/Common/UserCard/UserCardInfo/UserCardInfo.module.scss
  front/src/components/Letter/Letter/Letter.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/LetterDetail/LetterContent/LetterContent.module.scss
  front/src/components/LetterDetail/LetterContent/NewLetterContent.tsx
  front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.module.scss
  front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/components/Search/SearchFilterModal/SearchFilterModal.module.scss
  front/src/components/Search/SearchFilterModal/SearchFilterModal.tsx
  front/src/components/Search/SearchHeader/SearchHeader.module.scss
  front/src/components/Search/SearchHeader/SearchHeader.tsx
  front/src/components/Search/SearchLangTagFilter/SearchLangTagFilter.tsx
  front/src/components/Search/SearchList/SearchList.module.scss
  front/src/components/Search/SearchList/SearchList.tsx
  front/src/components/Search/SearchTag/SearchTag.module.scss
  front/src/components/Search/SearchTag/SearchTag.tsx
  front/src/components/Search/SearchTagFilter/SearchTagFilter.tsx
  front/src/components/Voca/VocaCard/VocaCard.module.scss
  front/src/dummy/searchUser.ts
  front/src/pages/MainPage.tsx
  front/src/pages/SearchPage.tsx
  front/src/recoil/atoms/letter/letter.ts
  front/src/recoil/atoms/search/index.ts
  front/src/recoil/atoms/search/search.ts
  front/src/utils/types/letter/letter.type.ts
  front/src/utils/types/tags/tags.ts
  front/src/utils/types/users/user.type.ts
Labels: FE

#108 [FE] 스와이퍼 슬라이더 너비 오류 수정
  front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.tsx
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
Labels: bug, FE

#109 [FE] fix: 메인 swiper 슬라이더 버그 수정
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
Labels: FE

#116 style: 마크업 구조 변경
  front/src/components/Common/LetterStatusIcon/LetterStatusIcon.tsx
  front/src/components/Letter/LetterList.tsx
  front/src/components/Search/SearchList/SearchList.tsx
Labels: FE

#113 [FE] 편지 조회 이미지 확대 모달
  front/src/App.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.module.scss
  front/src/components/LetterDetail/LetterPicture/LetterPictureWrapper.tsx
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
  front/src/components/PictureModal/PictureModal.module.scss
  front/src/components/PictureModal/PictureModal.tsx
  front/src/dummy/letter.ts
  front/src/index.css
  front/src/recoil/atoms/letter/letter.ts
  front/src/utils/types/letter/letter.type.ts
Labels: FE

#128 [FE] feat: 메인 도착한편지 & 추천 유저 API 적용
  front/src/assets/img/main/main_empty_letter.svg
  front/src/assets/img/main/main_envelope_cover.svg
  front/src/assets/img/main/main_envelope_empty.svg
  front/src/assets/img/main/main_letter_card.svg
  front/src/assets/img/main/main_waiting_owls.svg
  front/src/assets/img/main_waiting_owls.svg
  front/src/components/Main/MainLetters/MainLetter.module.scss
  front/src/components/Main/MainLetters/MainLetter.tsx
  front/src/components/Main/RecomandUser/RecomandUser.module.scss
  front/src/components/Main/RecomandUser/RecomandUser.tsx
  front/src/components/Main/RecomandUser/RecomandUserList.module.scss
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
  front/src/components/ProfileCompleted/Welcom.module.scss
  front/src/components/Welcome/Welcome.module.scss
Labels: FE

#127 [FE] feat: 회원 상세 조회 API 작업
  front/src/components/Common/Button/Button.module.scss
  front/src/components/Common/Button/Button.tsx
  front/src/components/Common/Modal/AlertModal.module.scss
  front/src/components/Common/Modal/FullPageModal.tsx
  front/src/components/Common/ProfileImage/ProfileImage.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Profile/Profile.tsx
  front/src/index.css
  front/src/recoil/atoms/user/user.ts
  front/src/recoil/atoms/user/userLanguage.ts
  front/src/recoil/atoms/user/userLocation.ts
  front/src/utils/common/index.ts
Labels: FE

#130 Be fix/hotfix ming
  back/src/main/java/com/mainproject/back/block/controller/BlockController.java
  back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
  back/src/main/java/com/mainproject/back/block/service/BlockService.java
  back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
  back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
  back/src/main/java/com/mainproject/back/follow/service/FollowService.java
  back/src/main/java/com/mainproject/back/member/dto/MemberDto.java
  back/src/main/java/com/mainproject/back/member/mapper/MemberMapper.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
Labels: bug, BE

#125 [FE] 편지 리스트 & 편지 유저 리스트 API 연결
  front/src/components/Common/Empty/Empty.module.scss
  front/src/components/Common/Empty/Empty.tsx
  front/src/components/Common/UserCard/UserCard.tsx
  front/src/components/Letter/Letter/Letter.tsx
  front/src/components/Letter/LetterList.module.scss
  front/src/components/Letter/LetterList.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/Letter/LetterWrapper/LetterWrapper.module.scss
  front/src/components/Letter/LetterWrapper/LetterWrapper.tsx
  front/src/dummy/letter.ts
  front/src/recoil/atoms/letter/letter.ts
  front/src/utils/date/index.ts
  front/src/utils/types/letter/letter.type.ts
Labels: FE

#132 [FE] 편지 상세 조회 페이지 API 연결
  front/src/components/Letter/LetterList.tsx
  front/src/components/Letter/LetterWrapper/LetterWrapper.tsx
  front/src/components/LetterDetail/LetterContent/LetterContent.module.scss
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
Labels: FE

#142 fix: 마이프로필 페이지 api 버그 수정중
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
Labels: FE

#145 fix: 태그 모달 useNavigate 오류 수정 & ModalProvider 위치 수정
  front/src/App.tsx
  front/src/components/Common/Modal/AlertModal.tsx
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Layouts/NoneLayout.tsx
  front/src/components/Login/Login.module.scss
  front/src/components/Login/Login.tsx
  front/src/components/Login/LoginMain.tsx
  front/src/components/Main/LifeQuotes/LifeQuotes.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Profile/Profile.tsx
  front/src/components/Start/Start.tsx
  front/src/context/AuthContext.tsx
  front/src/dummy/users.ts
  front/src/index.scss
  front/src/pages/LoginPage.tsx
  front/src/recoil/atoms/user/user.ts
  front/src/recoil/atoms/user/userTag.ts
  front/src/utils/axios/instanse.ts
  front/src/utils/types/auth/sign-in.type.ts
Labels: FE

#146 [FE] 단어장 CRUD API 연동
  front/src/components/Search/SearchHeader/SearchHeader.tsx
  front/src/components/Voca/Voca.module.scss
  front/src/components/Voca/Voca.tsx
  front/src/components/Voca/VocaCard/VocaCard.tsx
  front/src/components/Voca/VocaModal/VocaModal.module.scss
  front/src/components/Voca/VocaModal/VocaModal.tsx
  front/src/dummy/voca.ts
  front/src/recoil/atoms/voca/index.ts
  front/src/recoil/atoms/voca/voca.ts
  front/src/utils/types/voca/voca.type.ts
Labels: FE

#151 Be feat/vocabulary translate jin
  .idea/shelf/Uncommitted_changes_before_Update_at_2023_03_10_5_06_PM_[변경]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_2023_03_10_5_28_PM_[변경]/shelved.patch
  back/build.gradle
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/security/config/SecurityConfiguration.java
  back/src/main/java/com/mainproject/back/util/ApiManager.java
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
  back/src/main/java/com/mainproject/oauth/CustomOAuth2User.java
  back/src/main/java/com/mainproject/oauth/CustomOAuth2UserService.java
  back/src/main/java/com/mainproject/oauth/GoogleOAuth2UserInfo.java
  back/src/main/java/com/mainproject/oauth/OAuth2LoginFailureHandler.java
  back/src/main/java/com/mainproject/oauth/OAuth2LoginSuccessHandler.java
  back/src/main/java/com/mainproject/oauth/OAuthAttributes.java
  back/src/main/resources/application.yml
Labels: BE

#152 Be feat/vocabulary translate jin
  .idea/shelf/Uncommitted_changes_before_Update_at_2023_03_10_5_06_PM_[변경]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Update_at_2023_03_10_5_28_PM_[변경]/shelved.patch
  back/build.gradle
  back/src/main/java/com/mainproject/back/member/entity/Member.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/oauth/CustomOAuth2User.java
  back/src/main/java/com/mainproject/back/oauth/CustomOAuth2UserService.java
  back/src/main/java/com/mainproject/back/oauth/GoogleOAuth2UserInfo.java
  back/src/main/java/com/mainproject/back/oauth/OAuth2LoginFailureHandler.java
  back/src/main/java/com/mainproject/back/oauth/OAuth2LoginSuccessHandler.java
  back/src/main/java/com/mainproject/back/oauth/OAuthAttributes.java
  back/src/main/java/com/mainproject/back/security/config/SecurityConfiguration.java
  back/src/main/java/com/mainproject/back/util/ApiManager.java
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
  back/src/main/java/com/mainproject/back/vocabulary/entity/Vocabulary.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
  back/src/main/resources/application.yml
Labels: BE

#150 [FE] 검색 API 적용
  front/src/components/Letter/LetterList.tsx
  front/src/components/Search/SearchFilterModal/SearchFilterModal.tsx
  front/src/components/Search/SearchHeader/SearchHeader.tsx
  front/src/components/Search/SearchLangTagFilter/SearchLangTagFilter.tsx
  front/src/components/Search/SearchList/SearchList.module.scss
  front/src/components/Search/SearchList/SearchList.tsx
  front/src/components/Search/SearchTagFilter/SearchTagFilter.module.scss
  front/src/components/Search/SearchTagFilter/SearchTagFilter.tsx
  front/src/recoil/atoms/search/search.ts
  front/src/recoil/selectors/search/index.ts
  front/src/recoil/selectors/search/search.ts
Labels: FE

#153 [BE] 로그response값 , nation 제외 , 단어post시 response
  back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/tag/controller/TagController.java
  back/src/main/java/com/mainproject/back/util/RequestFilter.java
  back/src/main/java/com/mainproject/back/vocabulary/controller/VocabController.java
  back/src/main/java/com/mainproject/back/vocabulary/dto/VocabDto.java
Labels: BE

#158 [FE] feat: 편지 자물쇠 아이콘 css 및 hover animation 추가
  front/src/assets/img/common/icon_empty_envelope.svg
  front/src/assets/img/common/icon_locks.svg
  front/src/assets/img/common/owls_logo_w.svg
  front/src/components/Letter/Letter/Letter.module.scss
  front/src/components/Letter/Letter/Letter.tsx
Labels: FE

#162 [FE] 무한 스크롤 & 기타 버그 수정
  front/src/App.tsx
  front/src/components/BlackList/BlackList.tsx
  front/src/components/Following/Following.tsx
  front/src/components/Letter/LetterList.tsx
  front/src/components/Letter/LetterList/LetterList.module.scss
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.module.scss
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
  front/src/components/Voca/Voca.module.scss
  front/src/components/Voca/Voca.tsx
  front/src/components/Voca/VocaModal/VocaModal.tsx
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/LetterListPage.tsx
  front/src/pages/LetterUserListPage.tsx
  front/src/pages/UserLetterListPage.tsx
Labels: FE

#167 [FE] feat: #164 파비콘 & 타이틀 적용
  front/public/favicon.ico
  front/public/index.html
  front/src/App.tsx
  front/src/components/Layouts/RouterLayout.tsx
  front/src/utils/types/index.ts
  front/src/utils/types/router/index.ts
  front/src/utils/types/router/router.type.ts
Labels: FE

#168 [FE] fix: #165 UI 버그 수정
  front/src/assets/img/common/owls_friends.svg
  front/src/components/Common/Empty/Empty.module.scss
  front/src/components/Common/Modal/AlertModal.module.scss
  front/src/components/Intro/Intro.module.scss
  front/src/components/Layouts/BaseLayout.module.scss
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Layouts/NoneLayout.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/Login/Login.module.scss
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
  front/src/components/Main/RecomandUser/RecomandUserListItem.module.scss
  front/src/components/Main/RecomandUser/RecomandUserListItem.tsx
  front/src/components/MyProfile/LanguageSearchModal/LanguageSearchList.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.module.scss
  front/src/components/Profile/Profile.tsx
  front/src/components/Start/Start.module.scss
  front/src/components/Start/Start.tsx
  front/src/components/Welcome/Welcome.module.scss
  front/src/components/Welcome/Welcome.tsx
  front/src/context/AuthContext.tsx
  front/src/index.scss
  front/src/pages/WelcomePage.tsx
  front/src/utils/types/users/user.type.ts
Labels: FE

#170 [FE] 프로필 & 편지 이미지 첨부 기능 적용
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/utils/axios/fetch.ts
  front/src/utils/axios/instanse.ts
Labels: FE

#178 [FE] react toastify 적용 및 공통 options 설정
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/Intro/Intro.tsx
  front/src/components/Login/LoginMain.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/SignUp/SignUpMain.tsx
  front/src/context/AuthContext.tsx
  front/src/pages/IntroPage.tsx
  front/src/utils/axios/instanse.ts
  front/src/utils/index.ts
  front/src/utils/toast/index.ts
Labels: FE

#179 [FE] fix: 마이프로필 image css 수정, 불필요 css 파일 삭제 / 단어목록 Empty 컴포넌트 노출
  front/src/components/Common/ProfileImage/ProfileImage.module.scss
  front/src/components/MyProfile/MyProfileImage.module.scss
  front/src/components/Voca/Voca.tsx
Labels: FE

#183 fix : sql문 수정
  back/src/main/java/com/mainproject/back/block/controller/BlockController.java
  back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
  back/src/main/java/com/mainproject/back/block/service/BlockService.java
  back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
  back/src/main/java/com/mainproject/back/follow/dto/FollowDto.java
  back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
  back/src/main/java/com/mainproject/back/follow/service/FollowService.java
  back/src/main/java/com/mainproject/back/member/dto/MemberBlockDto.java
  back/src/main/java/com/mainproject/back/member/dto/MemberBlockInterface.java
  back/src/main/java/com/mainproject/back/member/dto/MemberLetterInterface.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
Labels: BE

#186 [FE] API URL 변경
  front/src/components/BlackList/BlackList.tsx
  front/src/components/Following/Following.tsx
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/components/Main/MainLetters/MainLetter.tsx
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/LanguageLevelModal/LanguageLevelModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Profile/Profile.tsx
  front/src/components/Search/SearchList/SearchList.tsx
  front/src/components/SignUp/SignUpMain.tsx
  front/src/context/AuthContext.tsx
  front/src/recoil/selectors/search/search.ts
  front/src/recoil/selectors/user/user.ts
  front/src/recoil/selectors/user/userLanguage.ts
  front/src/recoil/selectors/user/userLocation.ts
  front/src/recoil/selectors/user/userTag.ts
  front/src/utils/axios/fetch.ts
Labels: FE

#180 [BE] 배포 버전 코드 합치기
  .idea/dataSources.local.xml
  back/build.gradle
  back/src/main/java/com/mainproject/back/BackApplication.java
  back/src/main/java/com/mainproject/back/block/controller/BlockController.java
  back/src/main/java/com/mainproject/back/block/service/BlockService.java
  back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
  back/src/main/java/com/mainproject/back/image/config/AmazonS3Config.java
  back/src/main/java/com/mainproject/back/image/controller/ImageController.java
  back/src/main/java/com/mainproject/back/image/dto/ImageDto.java
  back/src/main/java/com/mainproject/back/image/exception/UploadExceptionCode.java
  back/src/main/java/com/mainproject/back/image/service/ImageService.java
  back/src/main/java/com/mainproject/back/init/InitDB.java
  back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
  back/src/main/java/com/mainproject/back/letter/controller/TranslateController.java
  back/src/main/java/com/mainproject/back/letter/dto/LetterPostDto.java
  back/src/main/java/com/mainproject/back/letter/repository/LetterRepository.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberBlockDto.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
  back/src/main/java/com/mainproject/back/security/config/SecurityConfiguration.java
  back/src/main/java/com/mainproject/back/security/oauth/CustomOAuth2User.java
  back/src/main/java/com/mainproject/back/security/oauth/CustomOAuth2UserService.java
  back/src/main/java/com/mainproject/back/security/oauth/GoogleOAuth2UserInfo.java
  back/src/main/java/com/mainproject/back/security/oauth/OAuth2LoginFailureHandler.java
  back/src/main/java/com/mainproject/back/security/oauth/OAuth2LoginSuccessHandler.java
  back/src/main/java/com/mainproject/back/security/oauth/OAuthAttributes.java
  back/src/main/java/com/mainproject/back/util/ApiManager.java
  back/src/main/java/com/mainproject/back/vocabulary/service/VocabService.java
  back/src/main/resources/application.yml
  back/src/test/java/com/mainproject/back/letter/LetterControllerTest.java
  back/src/test/java/com/mainproject/back/member/MemberControllerTest.java
  back/src/test/java/com/mainproject/back/vocabulary/VocabularyControllerTest.java
Labels: BE

#200 [FE-FIX] 친구 추가 API 오탈자 수정 & 단어 추가 버튼 추가
  front/src/components/Profile/Profile.tsx
  front/src/components/Voca/Voca.tsx
Labels: FE

#201 [FE-FIX] 편지 생성 API URL 오타 수정
  front/src/components/LetterDetail/NewLetterWrapper.tsx
Labels: FE

#196 [FE] feat: #185 img태그 onError 이벤트 처리
  front/src/assets/img/common/default_owls_error.svg
  front/src/assets/img/common/default_owls_thumb.svg
  front/src/assets/img/default_owls_thumb.svg
  front/src/components/Common/ProfileImage/ProfileImage.module.css
  front/src/components/Common/ProfileImage/ProfileImage.module.scss
  front/src/components/Common/ProfileImage/ProfileImage.tsx
  front/src/components/Common/RoundProfile/RoundProfile.tsx
  front/src/components/LetterDetail/LetterPicture/LetterPicture.tsx
  front/src/components/Main/RecomandUser/RecomandUserListItem.tsx
  front/src/components/PictureModal/PictureModal.tsx
  front/src/utils/image/index.ts
  front/src/utils/index.ts
Labels: FE

#197 [FE] feat: #184 편지 템플릿 적용하기
  front/src/assets/img/letter_type/type_0.svg
  front/src/assets/img/letter_type/type_01.svg
  front/src/assets/img/letter_type/type_02.svg
  front/src/assets/img/letter_type/type_1.svg
  front/src/assets/img/letter_type/type_2.svg
  front/src/assets/img/letter_type/type_3.svg
  front/src/components/Common/Modal/FullPageModal.tsx
  front/src/components/Common/PrevButton/PrevButton.tsx
  front/src/components/LetterDetail/LetterContent/LetterContent.module.scss
  front/src/components/LetterDetail/LetterContent/LetterContent.tsx
  front/src/components/LetterDetail/LetterContent/NewLetterContent.module.scss
  front/src/components/LetterDetail/LetterContent/NewLetterContent.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/LetterDetail/LetterType/LetterType.module.scss
  front/src/components/LetterDetail/LetterType/LetterType.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/index.scss
  front/src/pages/LoginPage.tsx
  front/src/pages/SignUpPage.tsx
  front/src/recoil/atoms/letter/index.ts
  front/src/recoil/atoms/letter/letterType.ts
  front/src/utils/types/index.ts
  front/src/utils/types/template/index.ts
Labels: FE

#206 fix/멤버 탈퇴시 조회기능 수정
  back/src/main/java/com/mainproject/back/block/mapper/BlockMapper.java
  back/src/main/java/com/mainproject/back/block/repository/BlockRepository.java
  back/src/main/java/com/mainproject/back/follow/mapper/FollowMapper.java
  back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
  back/src/main/java/com/mainproject/back/letter/exception/LetterExceptionCode.java
  back/src/main/java/com/mainproject/back/letter/mapper/LetterMapper.java
  back/src/main/java/com/mainproject/back/letter/service/LetterService.java
  back/src/main/java/com/mainproject/back/member/controller/MemberController.java
  back/src/main/java/com/mainproject/back/member/dto/MemberLetterDto.java
  back/src/main/java/com/mainproject/back/member/dto/MemberLetterInterface.java
  back/src/main/java/com/mainproject/back/member/dto/MemberSimpleDto.java
  back/src/main/java/com/mainproject/back/member/repository/MemberRepository.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
  back/src/main/java/com/mainproject/back/member/service/MemberService.java
  back/src/main/java/com/mainproject/back/vocabulary/mapper/VocabMapper.java
Labels: BE

#203 [FE] fix: #188 언어 및 태그 선택 유효성 체크 추가
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LanguageEditModal/LanguageListItem.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
Labels: FE

#209 [FE] fix: receiverId 프로퍼티 명 변경
  front/src/components/LetterDetail/NewLetterWrapper.tsx
Labels: FE

#207 [FE] 커서번역기 기능 편지디테일에 추가
  front/src/assets/img/Translate_icon.svg
  front/src/components/Common/CursorTranslation/CursorTranslation.module.scss
  front/src/components/Common/CursorTranslation/CursorTranslation.tsx
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/LetterDetail/LetterContent/LetterContent.tsx
  front/src/recoil/atoms/Translate/index.ts
Labels: FE

#210 feat: 탈퇴회원 편지리스트 랜더링 처리
  front/src/assets/img/cry_owls.svg
  front/src/components/Common/UserCard/UserCard.tsx
  front/src/components/Common/UserCard/UserQuit/UserQuit.module.scss
  front/src/components/Common/UserCard/UserQuit/UserQuit.tsx
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.module.scss
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
  front/src/utils/types/letter/user.type.ts
Labels: FE

#208 [FE] #204 이미지 업로드 파일 확장자 & 용량 유효성 체크 함수 작성
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/utils/image/index.ts
  package-lock.json
  package.json
Labels: FE

#211 [FE] 무한스크롤에 Suspense 로딩 스피너 적용
  front/src/components/BlackList/BlackList.module.scss
  front/src/components/BlackList/BlackList.tsx
  front/src/components/Common/LastInfinite/LastInfinite.tsx
  front/src/components/Common/RoundProfile/RoundProfile.module.scss
  front/src/components/Common/RoundProfile/RoundProfile.tsx
  front/src/components/Common/Spinner/InnerSpinner.tsx
  front/src/components/Common/Spinner/Spinner.module.scss
  front/src/components/Common/Spinner/Spinner.tsx
  front/src/components/Common/UserCard/NextUserCardList.tsx
  front/src/components/Common/UserCard/UserCard.module.scss
  front/src/components/Common/UserCard/UserCard.tsx
  front/src/components/Common/UserCard/UserQuit/UserQuit.module.scss
  front/src/components/Common/UserCard/UserQuit/UserQuit.tsx
  front/src/components/Following/Following.module.scss
  front/src/components/Following/Following.tsx
  front/src/components/Letter/Letter/Letter.module.scss
  front/src/components/Letter/Letter/Letter.tsx
  front/src/components/Letter/LetterList/LetterList.module.scss
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/Letter/LetterList/NextLetterList.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.module.scss
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/Search/SearchFilterModal/SearchFilterModal.tsx
  front/src/components/Search/SearchHeader/SearchHeader.module.scss
  front/src/components/Search/SearchHeader/SearchHeader.tsx
  front/src/components/Search/SearchLangTagFilter/SearchLangTagFilter.tsx
  front/src/components/Search/SearchList/SearchList.tsx
  front/src/components/Search/SearchTag/SearchTag.tsx
  front/src/components/Search/SearchTagFilter/SearchTagFilter.tsx
  front/src/components/Voca/RecentVocaList.tsx
  front/src/components/Voca/Voca.module.scss
  front/src/components/Voca/Voca.tsx
  front/src/components/Voca/VocaModal/VocaModal.tsx
  front/src/dummy/userList.ts
  front/src/index.tsx
  front/src/recoil/atoms/letter/letter.ts
  front/src/recoil/atoms/pagination/index.ts
  front/src/recoil/atoms/pagination/pagination.ts
  front/src/recoil/atoms/search/search.ts
  front/src/recoil/atoms/user/blacklist.ts
  front/src/recoil/atoms/user/following.ts
  front/src/recoil/atoms/user/index.ts
  front/src/recoil/atoms/user/user.ts
  front/src/recoil/atoms/voca/voca.ts
  front/src/recoil/selectors/letter/index.ts
  front/src/recoil/selectors/letter/letter.ts
  front/src/recoil/selectors/search/search.ts
  front/src/recoil/selectors/user/blacklist.ts
  front/src/recoil/selectors/user/follwing.ts
  front/src/recoil/selectors/voca/index.ts
  front/src/recoil/selectors/voca/voca.ts
  front/src/utils/types/letter/letter.type.ts
  front/src/utils/types/letter/user.type.ts
  front/src/utils/types/users/user.type.ts
  front/src/utils/types/voca/voca.type.ts
Labels: FE

#218 [FE] 단어장 모달 창 및 단어장 추가버튼 및 편지 작성 버튼 CSS 수정
  front/src/components/Common/Button/ButtonGroup.module.scss
  front/src/components/Common/Button/ButtonGroup.tsx
  front/src/components/Following/Following.tsx
  front/src/components/Profile/Profile.module.scss
  front/src/components/Search/SearchHeader/SearchHeader.tsx
  front/src/components/Voca/Voca.module.scss
  front/src/components/Voca/VocaModal/VocaModal.module.scss
  front/src/components/Voca/VocaModal/VocaModal.tsx
Labels: FE

#219 [FE] feat:친구 프로필에서 내가 선택한 언어 및 태그 활성화 표시 추가
  front/src/components/Profile/Profile.tsx
Labels: FE

#215 [FE] feat: #213 메인 단어장 API 적용 & 추천친구리스트 CSS 및 출력 수 수정
  front/src/components/Main/MainVoca/MainVocaCard.module.scss
  front/src/components/Main/MainVoca/MainVocaCard.tsx
  front/src/components/Main/RecomandUser/RecomandUserList.module.scss
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
Labels: FE

#214 [FE] fix: 라우터 이동시 401 에러 발생하면 인트로 페이지로 이동
  front/src/components/Layouts/BaseLayout.tsx
  front/src/components/Main/RecomandUser/RecomandUserListItem.module.scss
  front/src/components/MyProfile/LanguageEditModal/LanguageEditModal.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/TagEditModal/TagEditModal.tsx
  front/src/components/Start/Start.tsx
  front/src/context/AuthContext.tsx
  front/src/utils/axios/instanse.ts
Labels: FE

#220 fix: 잘못된 패키지 설치 경로 수정
  front/package-lock.json
  front/package.json
  package-lock.json
  package.json
Labels: bug, FE

#222 Be fix/is read ming
  back/src/main/java/com/mainproject/back/follow/controller/FollowController.java
  back/src/main/java/com/mainproject/back/follow/repository/FollowRepository.java
  back/src/main/java/com/mainproject/back/follow/service/FollowService.java
  back/src/main/java/com/mainproject/back/letter/controller/LetterController.java
  back/src/main/java/com/mainproject/back/letter/exception/LetterExceptionCode.java
  back/src/main/java/com/mainproject/back/letter/repository/LetterRepository.java
  back/src/main/java/com/mainproject/back/letter/service/LetterService.java
  back/src/main/java/com/mainproject/back/member/dto/FollowMemberInterface.java
  back/src/main/java/com/mainproject/back/member/dto/MemberLetterInterface.java
  back/src/main/java/com/mainproject/back/member/service/MemberConvertService.java
Labels: BE

#224 [FE] fix: 라우터 유효하지 않은 토큰 쿠키 제거 및 replace 로 경로 변경 수정
  front/src/utils/axios/instanse.ts
Labels: FE

#229 [FE] 해당유저와 교환한 편지 상태 UI 수정
  front/src/components/Common/LastInfinite/LastInfinite.module.scss
  front/src/components/Common/LetterStatusIcon/LetterStatusIcon.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
Labels: FE

#234 fix: Suspense 위치 수정
  front/src/App.tsx
Labels: FE

#236 [FE] fix:모바일기기에서 border-image-repeat 버그 현상 수정
  front/src/assets/img/letter_type/type_0.svg
  front/src/assets/img/letter_type/type_1.svg
  front/src/assets/img/letter_type/type_2.svg
  front/src/assets/img/letter_type/type_3.svg
  front/src/utils/types/template/index.ts
Labels: FE

#238 [FE] 편지에 이미지 추가가 안되던 문제 수정
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
Labels: bug, FE

#239 [FE] 프론트엔드 배포
  front/src/assets/img/letter_type/type_0.svg
  front/src/assets/img/letter_type/type_1.svg
  front/src/assets/img/letter_type/type_2.svg
  front/src/assets/img/letter_type/type_3.svg
  front/src/components/Letter/LetterList/LetterList.tsx
  front/src/components/LetterDetail/LetterDetailWrapper.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/utils/types/template/index.ts
Labels: bug, FE

#243 [FE] 편지작성 버튼 노출 및 시간 관련 로직 수정
  front/src/components/Letter/LetterList/LetterList.module.scss
  front/src/components/Profile/Profile.tsx
  front/src/utils/date/index.ts
Labels: FE

#244 [FE] fix: 단어장 의미 더보기 css 부분 수정
  front/src/components/LetterDetail/LetterContent/NewLetterContent.module.scss
  front/src/components/Voca/VocaCard/VocaCard.module.scss
  front/src/components/Voca/VocaCard/VocaCard.tsx
  front/src/components/Voca/VocaModal/VocaModal.module.scss
Labels: FE

#245 [FE] 편지 카드 넓이&높이 수정 및 border radius 수정
  front/src/components/Common/UserCard/UserCard.module.scss
  front/src/components/Letter/Letter/Letter.module.scss
  front/src/components/Letter/LetterList/LetterList.module.scss
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
Labels: FE

#247 [Fe] fix: 글 작성 중 페이지 이동 시 초기화 / 검색창에서 편지 보내지 못하는 오류 수정
  front/src/components/LetterDetail/LetterContent/NewLetterContent.tsx
  front/src/components/Search/SearchList/SearchList.tsx
Labels: FE

#248 [FE] 편지 작성 후, 뒤로가기 페이지가 다시 새 편지 작성 페이지가 아니도록 변경
  front/src/components/LetterDetail/NewLetterWrapper.tsx
Labels: FE

#249 [FE] 프론트엔드 배포
  front/src/components/Common/UserCard/NextUserCardList.tsx
  front/src/components/Common/UserCard/UserCard.module.scss
  front/src/components/Following/Following.tsx
  front/src/components/Letter/Letter/Letter.module.scss
  front/src/components/Letter/LetterList/LetterList.module.scss
  front/src/components/Letter/LetterList/NextLetterList.tsx
  front/src/components/Letter/LetterUserCard/LetterUserCard.module.scss
  front/src/components/LetterDetail/LetterContent/NewLetterContent.module.scss
  front/src/components/LetterDetail/LetterContent/NewLetterContent.tsx
  front/src/components/LetterDetail/NewLetterWrapper.tsx
  front/src/components/MyProfile/LocationEditModal/LocationEditModal.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/components/MyProfile/MyProfileImage.tsx
  front/src/components/Profile/Profile.tsx
  front/src/components/Search/SearchList/SearchList.tsx
  front/src/components/Voca/RecentVocaList.tsx
  front/src/components/Voca/VocaCard/VocaCard.module.scss
  front/src/components/Voca/VocaCard/VocaCard.tsx
  front/src/components/Voca/VocaModal/VocaModal.module.scss
  front/src/utils/date/index.ts
Labels: FE

#250 [FE] 검색 목록에서, 편지 보내는 UI 삭제 / 필요 없는 부분에 시간 UI 제거
  front/src/components/BlackList/BlackList.tsx
  front/src/components/Common/UserCard/NextUserCardList.tsx
  front/src/components/Following/Following.tsx
  front/src/components/Letter/LetterUserList/LetterUserList.tsx
  front/src/components/Search/SearchList/SearchList.tsx
Labels: bug, FE

#251 [FE] 메인 화면의 추천인이 새로고쳐지지않는 현상 수정
  front/src/components/Main/RecomandUser/RecomandUserList.tsx
Labels: bug, FE

#252 [FE] placeholder css 수정 및 생년월일 정규식, 필수 입력 체크, 로그아웃 relaod 수정
  front/src/components/Common/InputFeild/InputFeild.tsx
  front/src/components/MyProfile/MyProfile.tsx
  front/src/context/AuthContext.tsx
  front/src/index.scss
Labels: FE
